Update snorkell-auto-documentation.yml

diff --git a/.github/workflows/snorkell-auto-documentation.yml b/.github/workflows/snorkell-auto-documentation.yml
--- a/.github/workflows/snorkell-auto-documentation.yml
+++ b/.github/workflows/snorkell-auto-documentation.yml
@@ -31,12 +31,15 @@ jobs:
       - name: Run Script
         shell: bash
         run: |
+          ESCAPED_COMMIT_MSG=$(printf '%s\n' "${{ github.event.head_commit.message }}" | jq -R -s -c .)
+          echo "Escaped commit-msg: $ESCAPED_COMMIT_MSG"
           echo "Commit Message: ${{ github.event.head_commit.message }}"
-          # echo "Commit Message - First line: ${{ env.FIRST_LINE }}"
           echo "PR Title: ${{ env.PR_TITLE }}"
           echo "Repository: ${{ github.repository }}"
           echo "Branch Name: ${{ env.BRANCH_NAME}}"
           echo "Commit SHA: ${{ github.sha}}"
+          
           curl --max-time 600 -X POST -H 'api-key: ${{ secrets.SNORKELL_API_KEY }}' -H 'Content-Type: application/json' \
-          -d '{"installation_id": "${{ secrets.SNORKELL_CLIENT_ID }}", "full_repo_name": "${{ github.repository }}", "base_branch": "${{ env.BRANCH_NAME }}", "commit_sha": "${{ github.sha }}", "commit_message": "${{ github.event.head_commit.message }}"}' \
-          https://e53c-2401-4900-1f27-1a75-6816-1701-6a41-f280.ngrok-free.app/api/app/github/generate/documentation
+          -d '{"installation_id": "${{ secrets.SNORKELL_CLIENT_ID }}", "full_repo_name": "${{ github.repository }}", "base_branch": "${{ env.BRANCH_NAME }}", "commit_sha": "${{ github.sha }}", "commit_message": '"$ESCAPED_COMMIT_MSG"'}' \
+          https://e53c-2401-4900-1f27-1a75-6816-1701-6a41-f280.ngrok-free.app/api/app/github/generate/documentation || echo "Curl failed with exit code: $?"
+    
